### ISSUE TITLE
Error when enter random value during the begining of the game.

### ISSUE THREAD

**Issue by RechieKho** [ihave13digits/PythonTextRPG#14]
So during the begining of the game, there is a guy willing to give the player money. If you enter a random value, it causes and error.
Here is the error when I didn't enter anything.
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Documents/python_project/PythonTextRPG/main.py", line 5, in <module>
    E.start()
  File "/data/data/com.termux/files/home/Documents/python_project/PythonTextRPG/engine.py", line 1029, in start
    self.run()
  File "/data/data/com.termux/files/home/Documents/python_project/PythonTextRPG/engine.py", line 1033, in run
    self.update()
  File "/data/data/com.termux/files/home/Documents/python_project/PythonTextRPG/engine.py", line 1003, in update
    elif self.state == "quest": self.quest_menu()
                                ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/Documents/python_project/PythonTextRPG/engine.py", line 384, in quest_menu
    if 'part' in quest[self.selected_quest][part]['option'][sel]:
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: ''
```

**Comment by ihave13digits** [comment]
I fixed this bug, thanks for pointing it out for me.
